version: "3"
services:
  db:
    image: postgres
    platform: linux/x86_64
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
  webpacker:
    build: .
    volumes:
      - .:/blog_app
      - bundle:/usr/local/bundle
    environment:
      WEBPACKER_DEV_SERVER_HOST: 0.0.0.0
    command: ./bin/webpack-dev-server
    ports:
      - '3035:3035'
  web:
    build: .
    stdin_open: true
    tty: true
    volumes:
      - .:/blog_app
      - bundle:/usr/local/bundle
    command: bash -c "rm -rf tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      WEBPACKER_DEV_SERVER_HOST: webpacker
volumes:
  db:
    driver: local
  bundle:
    driver: local